### ISSUE TITLE
Plugin Crashing

### ISSUE THREAD

**Issue by ghost** [HPSoftware/octane-myitems2outlook#5] opened 2017-05-25 18:13 UTC
Unable to test added new functionality I am having issues with the "master" branch once built and installed outlook fails to load the plugin. However, when i use @slbruce "version-update" branch the plugin loads but still no remembered credentials or auto login with this branch, looks like @slbruce pulled from the most recent master.

**Comment by slbruce** [comment] 2017-05-28 05:55
@andrewlozoya Does the plugin work?  In other words - is the only problem that credentials are not remembered?
If there is a problem you can check the logs.  They should be found at c:\temp\OctaneMyItem.log

**Comment by ghost** [comment] 2017-05-30 14:11
@slbruce I cleared the log and attempted to fresh start to Outlook on a clean reboot, as you can see i was prompted to login with no remembered credentials. I then successfully manually re-entered my credentials and then quit Outlook to start a second time... again I was prompted with no remembered credentials... I have tried both the master and your 'version update' branch so i am confused on this. Thanks in advance, trying to resolve this so i can get the presales team in Plano to roll this out

`2017-05-30 09:01:27,984 [VSTA_Main] INFO OctaneMyItems.ThisAddIn - startup...
2017-05-30 09:01:28,046 [VSTA_Main] ERROR OctaneMyItems.Configuration - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'string' to 'int'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at OctaneMyItems.Configuration.LoadConfiguration()
2017-05-30 09:01:28,054 [VSTA_Main] INFO OctaneMyItemsSyncService.Services.OctaneService - Try relogin with user:andrew.lozoya@hpe.com
2017-05-30 09:01:28,125 [VSTA_Main] INFO OctaneMyItemsSyncService.Services.OctaneService - GetSharedSpaces
2017-05-30 09:01:28,166 [10] ERROR OctaneMyItems.Configuration - System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 ({"errorCode":"VALIDATION_TOKEN_EXPIRED_GLOBAL_TIME_OUT"}).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OctaneMyItemsSyncService.Services.OctaneService.<GetSharedSpaces>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OctaneMyItemsSyncService.Services.OctaneService.<TryReLogin>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OctaneMyItems.Configuration.<ConnectToServer>d__21.MoveNext()
2017-05-30 09:01:35,924 [10] INFO OctaneMyItemsSyncService.Services.OctaneService - login with user:andrew.lozoya@hpe.com
2017-05-30 09:01:36,141 [10] INFO OctaneMyItemsSyncService.Services.OctaneService - login successful with user:andrew.lozoya@hpe.com
2017-05-30 09:01:36,142 [10] INFO OctaneMyItemsSyncService.Services.OctaneService - GetSharedSpaces
2017-05-30 09:01:36,416 [10] INFO OctaneMyItemsSyncService.Services.OctaneService - GetSharedSpaces successful
2017-05-30 09:01:36,680 [10] INFO OctaneMyItemsSyncService.Services.OctaneService - GetWorkspaces
2017-05-30 09:01:37,133 [10] INFO OctaneMyItemsSyncService.Services.OctaneService - GetWorkspaces successful
2017-05-30 09:01:37,151 [10] INFO OctaneMyItemsSyncService.Services.OctaneService - SetDefaultSpace
2017-05-30 09:01:37,338 [10] INFO OctaneMyItemsSyncService.Services.OctaneService - SetDefaultSpace successful
2017-05-30 09:01:56,618 [VSTA_Main] INFO OctaneMyItems.ThisAddIn - startup...
2017-05-30 09:01:56,690 [VSTA_Main] ERROR OctaneMyItems.Configuration - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'string' to 'int'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at OctaneMyItems.Configuration.LoadConfiguration()
2017-05-30 09:01:56,700 [VSTA_Main] INFO OctaneMyItemsSyncService.Services.OctaneService - Try relogin with user:andrew.lozoya@hpe.com
2017-05-30 09:01:56,775 [VSTA_Main] INFO OctaneMyItemsSyncService.Services.OctaneService - GetSharedSpaces
2017-05-30 09:01:56,828 [4] INFO OctaneMyItemsSyncService.Services.OctaneService - GetSharedSpaces successful
2017-05-30 09:01:57,053 [4] INFO OctaneMyItemsSyncService.Services.OctaneService - GetSharedSpaces
2017-05-30 09:01:57,096 [4] INFO OctaneMyItemsSyncService.Services.OctaneService - GetSharedSpaces successful
2017-05-30 09:01:57,096 [4] ERROR OctaneMyItems.Configuration - System.NullReferenceException: Object reference not set to an instance of an object.
   at OctaneMyItems.Configuration.<ConnectToServer>d__21.MoveNext()
`

**Comment by ghost** [comment] 2017-05-30 15:51
I noticed something interesting I believe some old config or registry files have been left over from my previous install of this plugin... once i cancel/close the octane login prompt on outlook startup. I can then go to the plugin tab and click config actually see the credentials being actually stored there... i since attempted to clean the registry entries and install directory but i am still having the prompt on startup... I will be happy to send a video please let me know

**Comment by xiajingchun** [comment] 2017-05-30 15:56
@xintian01 @albertwoo  please have a look too.

**Comment by ghost** [comment] 2017-05-31 17:49
I believe this is the issue it is timing out too soon or the connectToServer method is not working properly so it is ShowConfigurationForm everytime...

`      if (await ConnectToServer())
        m_initialized = true;
      else
        ShowConfigurationForm();
    }`

**Comment by albertwoo** [comment] 2017-06-02 04:49
According to the log and the source code, I think the problem is that we did not convert data type correctly in method LoadConfiguration for SharedSpaceId and WorkSpaceId.
I committed a fix.

**Closed as completed by albertwoo** 2017-06-02 04:49 UTC
Labels: question
